name: Minicube Deployment
on:
  workflow_dispatch:

jobs:
  Deploy:
    runs-on: ubuntu-24.04
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"
    name: build nodejs-app and deploy to minikube

    steps:
      - uses: actions/checkout@v4

      - name: Start minikube
        uses: medyagh/setup-minikube@latest

      - name: Try the cluster!
        run: kubectl get pods -A

      - name: Build image
        run: |
          minikube image build -t dhulakachare/nodejs-app:latest .

      - name: Deploy to minikube
        run: |
          kubectl apply -f deploy-k8s.yml
          kubectl wait --for=condition=available deployment/nodejs-app-deployment --timeout=120s

      - name: Test service URLs
        run: |
          minikube service list
          minikube service nodejs-app-service --url
          echo "------------------opening the service------------------"
          curl $(minikube service nodejs-app-service --url)
