name: Minicube Deployment
on:
  workflow_dispatch:

jobs:
  Deploy:
    runs-on: ubuntu-24.04
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"
    name: build nodejs-app and deploy to minikube

    steps:
      - uses: actions/checkout@v4
        with:
          repository: medyagh/local-dev-example-with-minikube

      - name: Start minikube
        uses: medyagh/setup-minikube@latest

      - name: Try the cluster!
        run: kubectl get pods -A

      - name: Build image
        run: |
          minikube image build -t local/nodejs-app:v1 .

      - name: Deploy to minikube
        run: |
          kubectl apply -f deploy-k8s.yml
          kubectl wait --for=condition=ready pod -l app=local/nodejs-app

      - name: Test service URLs
        run: |
          minikube service list
          minikube service local-nodejs-app-svc --url
          echo "------------------opening the service------------------"
          curl $(minikube service local-nodejs-app-svc --url)
