# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
# It performs the following steps:

# Step 1: Check out the source code.
# Step 2: Set up different versions of Node.js for testing.
# Step 3: Perform a clean install of Node.js dependencies.
# Step 4: Cache and restore dependencies for faster builds.
# Step 5: Build the source code.
# Step 6: Run tests using different versions of Node.js.

name: Node.js CI

on:
  push:
    branches: [ "main" ]  # Trigger the workflow on every commit to the main branch.
  pull_request:
    branches: [ "main" ]  # Trigger the workflow on pull requests targeting the main branch.

jobs:
  Test:
    runs-on: ubuntu-24.04
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4  # Step 1: Check out the source code from the repository.

    - name: Set up Node.js
      uses: actions/setup-node@v4 # Step 2: Set up the specified version of Node.js for testing.*/
      with:
        node-version: 24
        cache: 'npm' # Step 4: Cache and restore dependencies for faster builds.

    - name: Install Node.js dependencies
      run: npm ci # Step 3: Perform a clean install of Node.js dependencies.

    - name: Run tests
      run: npm run test # Step 4: Run tests using the specified Node.js version.

  Build:
    needs: Test 
    runs-on: ubuntu-24.04
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4 

    - name: Set up Node.js
      uses: actions/setup-node@v4 
      with:
        node-version: 24
        cache: 'npm'

    - name: Install Node.js dependencies
      run: npm ci

    - name: Run tests
      run: npm run test

    - name: Build Website
      run: npm run build

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: |
          dist
          package.json
        
  Deploy:
    needs: Build
    runs-on: ubuntu-24.04
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4 

    - name: Download Build Artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-artifacts

    - name: Output Contents
      run:
          ls

    - name: Deploy to Server
      run: echo "Deploying to server..."