# This CICD workflow performs following actions:
# Step 1: Check out the source code.
# Step 2: Set up different versions of Node.js for testing.
# Step 3: Perform a clean install of Node.js dependencies.
# Step 4: Cache and restore dependencies for faster builds.
# Step 5: Build the source code.
# Step 6: Run tests using different versions of Node.js.

name: Node.js CI

on:
  push:
    branches: [ "main" ]  # Trigger the workflow on every commit to the main branch.
  pull_request:
    branches: [ "main" ]  # Trigger the workflow on pull requests targeting the main branch.

jobs:
  Test:
    runs-on: ubuntu-24.04
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4  # Step 1: Check out the source code from the repository.

    - name: Cache Depenedencies
      uses: actions/cache@v4 # Step 4: Cache and restore dependencies for faster builds.
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

    - name: Set up Node.js
      uses: actions/setup-node@v4 # Step 2: Set up the specified version of Node.js for testing.*/
      with:
        node-version: 24
        cache: 'npm' # Step 4: Cache and restore dependencies for faster builds.

    - name: Install Node.js dependencies
      run: npm ci # Step 3: Perform a clean install of Node.js dependencies.

    - name: Run tests
      run: npm run test # Step 4: Run tests using the specified Node.js version.

  Build:
    needs: Test 
    runs-on: ubuntu-24.04
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4 
    
    - name: Cache Depenedencies
      uses: actions/cache@v4 # Step 4: Cache and restore dependencies for faster builds.
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

    - name: Set up Node.js
      uses: actions/setup-node@v4 
      with:
        node-version: 24
        cache: 'npm'

    - name: Install Node.js dependencies
      run: npm ci

    - name: Run tests
      run: npm run test

    - name: Build Website
      run: npm run build

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: |
          dist
          package.json

    - name: Download Build Artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-artifacts
    - name: Output Contents
      run:
          ls    
        
  Build-Push-Docker-Image:
    needs: Build
    runs-on: ubuntu-24.04
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
  
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v6
      with:
        context: . # Looks for the Dockerfile in the root directory
        file: ./Dockerfile
        push: true
          # Tags the image as 'latest' and with the unique GitHub commit SHA
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/node-app:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/node-app:${{ github.sha }}
          # Enables GitHub Actions caching to speed up future builds
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
    - name: Deploy to Server
      run: echo "Deploying to server..."